[package]
name = "db_project"
version = "0.1.0"
edition = "2021"

[dependencies]
mysql = "23.0"
tokio = { version = "1", features = ["full"] }
eframe = "0.26"   # GUI (egui)
serde = { version = "1.0", features = ["derive"] }
dotenvy = "0.15"
